spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/coffee
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    show-sql: true
